ENV                     = "prod" 

# MySQL Variable Values 
RDS_MYSQL_PORT = 3306
RDS_MYSQL_STORAGE = 10
RDS_MYSQL_ENGINE_VERSION = "5.7"
RDS_INSTANCE_TYPE = "db.t3.micro"

# DocDB Values
DOCDB_PORT = 27017
DOCDB_INSTACE_CLASS = "db.t3.medium"
DOCDB_INSTACE_COUNT = 1
